# Generated by Django 3.2.3 on 2021-09-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
